alter table public.organization_settings
  add column if not exists legacy_id bigint generated by default as identity,
  add column if not exists cert_last_checked_at timestamptz,
  add column if not exists cert_alert_last_sent_at timestamptz;

update public.organization_settings
set legacy_id = default
where legacy_id is null;

alter table public.organization_settings
  alter column legacy_id set not null;

create unique index if not exists idx_organization_settings_legacy_id
  on public.organization_settings (legacy_id);

alter table public.organization_integrations
  add column if not exists popbill_is_test boolean not null default false;

alter table public.managed_customers
  add column if not exists legacy_id bigint generated by default as identity;

update public.managed_customers
set legacy_id = default
where legacy_id is null;

alter table public.managed_customers
  alter column legacy_id set not null;

create unique index if not exists idx_managed_customers_legacy_id
  on public.managed_customers (legacy_id);

alter table public.inbox_messages
  add column if not exists legacy_id bigint generated by default as identity;

update public.inbox_messages
set legacy_id = default
where legacy_id is null;

alter table public.inbox_messages
  alter column legacy_id set not null;

create unique index if not exists idx_inbox_messages_legacy_id
  on public.inbox_messages (legacy_id);

alter table public.invoice_drafts
  add column if not exists legacy_id bigint generated by default as identity;

update public.invoice_drafts
set legacy_id = default
where legacy_id is null;

alter table public.invoice_drafts
  alter column legacy_id set not null;

create unique index if not exists idx_invoice_drafts_legacy_id
  on public.invoice_drafts (legacy_id);

alter table public.app_logs
  add column if not exists legacy_id bigint generated by default as identity;

update public.app_logs
set legacy_id = default
where legacy_id is null;

alter table public.app_logs
  alter column legacy_id set not null;

create unique index if not exists idx_app_logs_legacy_id
  on public.app_logs (legacy_id);
