create table if not exists public.customer_certificates (
  id uuid primary key default gen_random_uuid(),
  legacy_id bigint generated by default as identity,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  managed_customer_id uuid not null references public.managed_customers(id) on delete cascade,
  certificate_kind text not null default 'unknown',
  certificate_name text not null default '',
  certificate_usage_name text not null default '',
  issuer_name text not null default '',
  certificate_serial text,
  certificate_user_dn text,
  certificate_oid text,
  expire_date date,
  cert_dir_path text,
  is_primary boolean not null default false,
  link_source text not null default 'manual',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint customer_certificates_kind_check check (
    certificate_kind in ('electronic_tax', 'general_personal', 'general_business', 'unknown')
  ),
  constraint customer_certificates_link_source_check check (
    link_source in ('auto', 'manual')
  )
);
update public.customer_certificates
set legacy_id = default
where legacy_id is null;
alter table public.customer_certificates
  alter column legacy_id set not null;
create unique index if not exists idx_customer_certificates_legacy_id
  on public.customer_certificates (legacy_id);
create index if not exists idx_customer_certificates_org_customer
  on public.customer_certificates (organization_id, managed_customer_id);
create index if not exists idx_customer_certificates_org_serial
  on public.customer_certificates (organization_id, certificate_serial);
create index if not exists idx_customer_certificates_org_user_dn
  on public.customer_certificates (organization_id, certificate_user_dn);
drop trigger if exists trg_customer_certificates_set_updated_at on public.customer_certificates;
create trigger trg_customer_certificates_set_updated_at
before update on public.customer_certificates
for each row
execute function public.set_updated_at();
