create table if not exists public.renewal_agent_heartbeats (
  agent_id text primary key,
  hostname text not null,
  version text not null,
  os text not null,
  process_json jsonb not null default '{}'::jsonb,
  bridge_json jsonb not null default '{}'::jsonb,
  notes_json jsonb not null default '[]'::jsonb,
  received_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index if not exists idx_renewal_agent_heartbeats_received_at
  on public.renewal_agent_heartbeats (received_at desc);
drop trigger if exists trg_renewal_agent_heartbeats_set_updated_at on public.renewal_agent_heartbeats;
create trigger trg_renewal_agent_heartbeats_set_updated_at
before update on public.renewal_agent_heartbeats
for each row
execute function public.set_updated_at();
alter table public.renewal_agent_heartbeats enable row level security;
create table if not exists public.renewal_automation_jobs (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('bridge-probe', 'certid-probe', 'renewal-preflight')),
  status public.job_status not null default 'queued' check (status in ('queued', 'claimed', 'completed', 'failed')),
  customer_id integer,
  customer_name text,
  certificate_index integer,
  certificate_cn text,
  requested_by text not null default '',
  claimed_by text,
  summary text not null default '',
  error text,
  result_json jsonb,
  comparison_profile_json jsonb,
  submission_profile_json jsonb,
  execute_submit boolean not null default false,
  requested_at timestamptz not null default timezone('utc', now()),
  claimed_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index if not exists idx_renewal_automation_jobs_status_requested_at
  on public.renewal_automation_jobs (status, requested_at, id);
create index if not exists idx_renewal_automation_jobs_requested_by_requested_at
  on public.renewal_automation_jobs (requested_by, requested_at desc, id desc);
drop trigger if exists trg_renewal_automation_jobs_set_updated_at on public.renewal_automation_jobs;
create trigger trg_renewal_automation_jobs_set_updated_at
before update on public.renewal_automation_jobs
for each row
execute function public.set_updated_at();
alter table public.renewal_automation_jobs enable row level security;
create or replace function public.claim_next_renewal_automation_job(
  p_agent_id text,
  p_claim_timeout_seconds integer default 180
)
returns setof public.renewal_automation_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claim_timeout interval := make_interval(secs => greatest(coalesce(p_claim_timeout_seconds, 180), 1));
  v_now timestamptz := timezone('utc', now());
  v_job public.renewal_automation_jobs%rowtype;
begin
  update public.renewal_automation_jobs
  set
    status = 'queued',
    claimed_at = null,
    claimed_by = null,
    finished_at = null,
    error = '이전 에이전트 응답이 없어 대기열로 재등록했습니다.',
    summary = case
      when type = 'certid-probe' then
        coalesce(nullif(btrim(certificate_cn), ''), case when certificate_index is not null then '인증서 #' || certificate_index::text else '인증서' end)
        || ' certID 조회 재대기'
      when type = 'renewal-preflight' then
        coalesce(nullif(btrim(certificate_cn), ''), case when certificate_index is not null then '인증서 #' || certificate_index::text else '인증서' end)
        || ' 갱신 경로 분석 재대기'
      else
        coalesce(nullif(btrim(customer_name), ''), '인증서 목록') || ' 진단 재대기'
    end,
    updated_at = v_now
  where status = 'claimed'
    and claimed_at is not null
    and claimed_at <= (v_now - v_claim_timeout);

  select *
  into v_job
  from public.renewal_automation_jobs
  where status = 'queued'
  order by requested_at asc, id asc
  for update skip locked
  limit 1;

  if not found then
    return;
  end if;

  update public.renewal_automation_jobs
  set
    status = 'claimed',
    claimed_by = p_agent_id,
    claimed_at = v_now,
    error = null,
    summary = case
      when type = 'certid-probe' then
        coalesce(nullif(btrim(certificate_cn), ''), case when certificate_index is not null then '인증서 #' || certificate_index::text else '인증서' end)
        || ' certID 조회 실행 중'
      when type = 'renewal-preflight' then
        coalesce(nullif(btrim(certificate_cn), ''), case when certificate_index is not null then '인증서 #' || certificate_index::text else '인증서' end)
        || ' 갱신 경로 분석 실행 중'
      else
        coalesce(nullif(btrim(customer_name), ''), '인증서 목록') || ' 진단 실행 중'
    end,
    updated_at = v_now
  where id = v_job.id
  returning * into v_job;

  return next v_job;
  return;
end;
$$;
